

# there are 14 regions that the public health units are in
kingston_area <- c("KINGSTON", "SOUTH FRONTENAC", "ADDINGTON HIGHLANDS", "CENTRAL FRONTENAC", "FRONTENAC ISLANDS", "GANANOQUE", "GREATER NAPANEE", "LOYALIST", "STONE MILLS", "ABBEY", "ANGLIN")
belleville_area <- c("ASPHODEL-NORWOOD", "BANCROFT", "BELLEVILLE", "BRIGHTON", "CENTRE HASTINGS", "COBOURG", "CRAMAHE", "DESERONTO", "MADOC", "MARMORA AND LAKE", "PRINCE EDWARD COUNTY", "PRINCE EDWARD ISLAND", "QUINTE WEST", "STIRLING-RAWDON", "TRENT HILLS", "TWEED", "HASTINGS HIGHLANDS", "HAVELOCK-BELMONT-METH", "TUDOR AND CASHEL")
brockville_area <- c("LEEDS & THOUSAND ISL", "ATHENS", "AUGUSTA", "BROCKVILLE", "EDWARDSBURGH/CARDINAL", "ELIZABETHTOWN-KITLEY", "MERRICKVILLE-WOLFORD",  "NORTH GRENVILLE", "PERTH", "PRESCOTT", "SMITHS FALLS", "CASSELMAN", "LANSDOWNE HOUSE", "SOUTH STORMONT")
north_area <- c("ATTAWAPISKAT 91A", "FORT ALBANY 67", "MOOSE FACTORY 68", "MOOSE FACTORY ISLAND", "COCHRANE DISTRICT", "MOOSONEE") # this really refers to Hudson Bay/James Bay (not like Sault Ste Marie)
distant_area <- c("ACADIA", "AJAX", "ALBERTA", "ALNWICK/HALDIMAND", "AMHERSTBURG", "BARRIE", "BENEDICKSON", "BLUE MOUNTAINS", "BLUEWATER", "BONNECHERE VALLEY", "BRACEBRIDGE", "BRADFORD W GWILLIM.", "BRAMPTON", "BRANTFORD", "BRIGHTON", "BRITISH COLUMBIA", "BURLINGTON", "Caledon", "CAMBRIDGE", "CANADA REMAINING", "CARLETON PLACE", "CARLOW/MAYO", "CAVAN-MILLBROOK-N MON", "CENTRE WELLINGTON", "CHAPLEAU", "Chatham-Kent", "CLARENCE-ROCKLAND", "CLARINGTON", "CORNWALL", "CURVE LAKE FRST NTN35", "ELLIOT LAKE", "ESSA", "FRONT OF YONGE", "GREATER SUDBURY", "GRIMSBY", "GUELPH", "GUELPH/ERAMOSA", "HALTON HILLS", "HAMILTON (city)", "HAMILTON (Northumberland)", "HEARST", "HUNTSVILLE", "KAWARTHA LAKES", "KINGSVILLE", "KITCHENER",  "LA SALLE", "LAKESHORE",  "LAMBTON SHORES", "LANARK HIGHLANDS", "LINCOLN", "LONDON", "MADAWASKA VALLEY", "MANITOBA EXC. INDIANS",  "Markham", "MIDDLESEX CENTRE", "MILTON", "MISSISSAUGA", "NEW BRUNSWICK", "NEWFOUNDLAND/LABRADR", "NEWMARKET", "NIAGARA FALLS", "NIAGARA-ON-THE-LAKE", "NORFOLK COUNTY", "NORTH BAY", "NORTH DUNDAS", "NORTH FRONTENAC", "NORTH GLENGARRY", "NOVA SCOTIA", "NUNAVUT", "OAKVILLE", "ORILLIA", "OSHAWA",  "OTONABEE-S MONAGHAN", "OTTAWA", "PEAWANUCK",  "PEMBROKE", "PETAWAWA", "PETERBOROUGH", "PICKERING", "PRINCE EDWARD ISLAND", "PORT COLBORNE", "PORT HOPE", "QUEBEC", "Richmond Hill", "RIDEAU LAKES", "RUSSELL", "SARNIA", "SASKATCHEWAN", "SCHREIBER",  "SCUGOG",  "SMITH-ENNISMORE-LAKEF", "ST. CATHARINES", "TAY VALLEY", "TEMISKAMING SHORES, TIMISKAMING", "THOROLD", "THUNDER BAY", "TORONTO", "TYENDINAGA", "TYENDINAGA MOHAWK TER", "U.S.A. Remaining", "VAUGHAN", "WASAGA BEACH", "WATERLOO", "WEST LINCOLN",  "WESTPORT", "WHITBY", "Whitchurch-Stouffvil", "WILMOT", "WINDSOR", "World Other", "YUKON TERRITORY", "ADELAIDE METCALFE", "ANDERSON", "ARNPRIOR", "AURORA", "BAYHAM", "BLANDFORD-BLENHEIM", "BRANT COUNTY", "BROCK", "BROCKTON", "CLEARVIEW", "COLLINGWOOD", "DAWN-EUPHEMIA", "ESPANOLA", "ESSEX", "GEORGINA", "HALDIMAND", "Hanover", "HAWKESBURY", "IGNACE", "INNISFIL", "KENORA", "KING", "MANITOUWADGE", "MCNAB/BRAESIDE", "MISSISSIPPI MILLS", "NEW TECUMSETH", "NEW YORK", "NORTH ALGONA WILBER.", "NORTHEAST MANITOULIN", "NORTHWEST TERRITORIES", "ORANGEVILLE", "OWEN SOUND", "PERTH EAST", "PETROLIA", "PLUMMER ADDITIONAL", "POINT EDWARD", "PUSLINCH", "RENFREW", "SAULT STE. MARIE", "SOUTH BRUCE PENINSULA", "SOUTH DUNDAS", "SOUTH GLENGARRY", "SOUTH RIVER", "SOUTHWEST MIDDLESEX", "ST. THOMAS", "Stratford", "TIMMINS", "TINY", "UXBRIDGE", "WELLAND", "WELLESLEY", "WEST PERTH", "WOODSTOCK", "WOOLWICH")

# for disposition column
outpatient_no_cas <- c("Frontenac Youth Services - Oshawa (CM)",                   
                       "GROUP LIVING/SUPP HOUSING - (Generic)",
                       "HOME CARE PROGRAM - (Generic)",
                       "home",
                       "HOME CARE PROGRAM - (Generic)",
                       "Kingston Front Lennox & Addn Ccac - Kingston (HC)",
                       "MIDWIFE - (Generic)", "South East CCAC - Kingston (HC)",
                       "TRANSIT.HOUSING/SHELTER - (Generic)")
outpatient_cas <- c("Catholic Childrens Aid Society Central - Toronto (CA)",     
                    "Child And Family Serv.For Timmins And D - Timmins (CA)",    
                    "CHILDREN AID SOCIETY - (Generic)",                          
                    "Childrens Aid Soc Of County Of Lanark - Perth (CA)",        
                    "Childrens Aid Soc.Counties Of Stormont - Cornwall (CA)",   
                    "Childrens Aid Soc.District Of Nipissing - North Bay (CA)", 
                    "Childrens Aid Soc.For Dist Of Nipissing - Parry Sound (CA)",
                    "Childrens Aid Soc.Of County Of Frontena - Kingston (CA)",  
                    "Childrens Aid Soc.Of County Of Leeds - Brockville (CA)",   
                    "Childrens Aid Soc.Of Ottawa-Carleton - Gloucester (CA)",   
                    "Childrens Aid Soc.Of Tor East Branch - Toronto (CA)",      
                    "Childrens Aid Society - Toronto (CA)",                     
                    "Childrens Aid Society Of Northumberland - Cobourg (CA)",   
                    "Childrens Aid Society Of Prince Edward - Picton (CA)",     
                    "Childrens Aid Society Of Toronto - Toronto (CA)",          
                    "Childrens Hospital Of Eastern Ontario - Ottawa (AM)",      
                    "Childrens Hospital Of Eastern Ontario - Ottawa (AP)",      
                    "Durham Childrens Aid Society - Oshawa (CA)",               
                    "Family And Childrens Serv Of Renfrew Co - Pembroke (CA)",  
                    "Hastings Childrens Aid Society - Belleville (CA)",         
                    "Kawartha-Haliburton Childrens Aid Soc - Peterborough (CA)",
                    "Kenora-Patricia Child And Family Service - Kenora (CA)",   
                    "Lennox-Addington Family And Childrens S - Napanee (CA)")
inpatient <- c("Cornwall Community Hospital - Ambulatory (2nd Street Site)",
               "DETOXIFICATION CENTRE - (Generic)",
               "Hospital For Sick Children - Toronto (AM)",                
               "Hospital For Sick Children - Toronto (AP)",                
               "HOTEL DIEU HOSPITAL",                                      
               "Hotel Dieu Hospital-Kingston - Kingston (MC)",
               "Kingston General Hospital - Kingston (AM)",                
               "Kingston General Hospital - Kingston (AP)",                
               "KINGSTON GENERAL HOSPITAL (MH)",                           
               #"Kingston Health Sciences Centre - HDH (DAD)", #this one is only in 2023 it seems            
               "Kingston Health Sciences Centre - HDH (NACRS)",            
               "Kingston Health Sciences Centre - KGH (NACRS)",            
               "Kingston Health Sciences Centre -KGH (DAD)",
               "Patricia Centre For Children & Youth - Dryden (CM)",
               "Quinte Healthcare Corporation-Belleville - Belleville (AM)",
               "Quinte Healthcare Corporation-Belleville - Belleville (AP)",
               "UNCLASSIFIED HEALTH INST - (Generic)")

#referred_from
facility <- c("Ambulatory Care Service (Reporting or other Facility)", "Community Health Service (Includes Public Health, telehealth)", "Drug Dependency Service (Detoxification Service)", "Educational Agency (School)", "Home Care", "Inpatient Facility (reporting Or Other Facility)", "Legal Service (Police, Parole Officer, Court Correctional facility, Jail)", "NULL", "Other (for Example: Place Of Employment, Mental Health Community)", "Private Practice", "Residential Care Facility (E.g.: Retirement / Nursing home, Chronic Care facility, Rehab facility, Group Home)")

#cacs_dx
cardiovasc <- c("Acute Myocardial Infarction/Angina",
                "Angiography",
                "Cardiovascular Condition with Acute Admission/Transfer",
                "Chest Pain Not Yet Diagnosed with or without Moderate or Minor Intervention",
                "Congenital Heart Disease",
                "Congestive Heart Failure",
                "Disease or Disorder of the Peripheral Vascular System with or without Minor Intervention",
                "Vascular Injury",
                "Vascular Intervention - Grade 2", 
                "Vascular Problems",
                "Shock",
                "Thoraco-Abdominal And Major Vascular Injuries",
                "Other Trauma or Shock with or without Minor Intervention", 
                "Other Trauma, Shock (without admission/interventio", 
                "Other Trauma, Shock (without admission/intervention)",
                "MINOR INVESTIGATIVE GENERAL CIRCULATORY SYSTEM", 
                "Open Wound and Vascular Injury",
                "Open Wound or Vascular Injury with Minor Intervention",
                "Open Wound or Vascular Injury without Intervention",
                "Other Disease or Disorder Cardiac System", 
                "Other Disease or Disorder of the Cardiac System with or without Moderate or Minor Intervention",
                "Disease or Disorder Vascular System", 
                "Disease/Disorder Cardiovascular System with Acute Admission/Transfer without High Resource Interv",
                "Dysrhythmia And Conductive Disorders",
                "General Circulatory System", 
                "General Circulatory System with Minor Investigatio", 
                "General Circulatory System with Minor Investigation",
                "General Circulatory System with Minor Investigativ", 
                "General Circulatory System with Minor Investigative Technology",
                "MANAGEMENT GENERAL CIRCULATORY SYSTEM",
                "MINOR VASCULAR PROCEDURES",
                "Inflammatory Cardiac Disorders")

derm <- c("Burn",
          "Burn with or without Minor Intervention",
          "Disease or Disorder of the Skin or Breast with or without Minor Intervention",
          "Skin And Subcutaneous Tissue - Age 0 - 17 Yrs",
          "Skin And Subcutaneous Tissue - Age 18 + Yrs", 
          "Skin And Subcutaneous Tissue with Minor Investigat", 
          "Skin And Subcutaneous Tissue with Minor Investigation",
          "Skin And Subcutaneous Tissue with Minor Investigative Technology",
          "Skin Disorders and Injuries", 
          "SKIN PROCEDURES",
          "Soft Tissue Intervention", 
          "Other Skin Intervention - Grade 1",
          "Other Skin Intervention - Grade 1 - Local/No Anaes", 
          "Other Skin Intervention - Grade 1 - Local/No Anaesthesia/Other Unmonitored",
          "Other Skin Intervention - Grade 1- Other Nerve Block/Monitored Anaestic",
          "Other Skin Intervention - Grade 2",
          "Disease or Disorder Skin & Breast",
          "MANAGEMENT SKIN AND SUBCUTANEOUS TISSUE, AGE 0 - 1",
          "Minor Burns",
          "MINOR INVESTIGATIVE SKIN AND SUBCUTANEOUS TISSUE",
          "Moderate To Severe Burns",
          "Open Wound",
          "Open Wound With Complication",
          "Open Wounds Without Complication", 
          "OPEN WOUNDS WITHOUT COMPLICATION")

endocrine_renal_fluid <- c("Diabetes - Age 0 - 17 Yrs",
                           "Diabetes or Glucose Intolerance with or without Minor Intervention",
                           "Diabetes/Glucose Intolerance",
                           "Fluid And Electrolyte Conditions", 
                           "FLUID AND ELECTROLYTE CONDITIONS", 
                           "Thyrotoxicosis", 
                           "Renal Failure & Other Disorders of the Kidney/Ureter",
                           "Renal Failure and Other Disorders of the Kidney or Ureter with or without Minor Intervention", 
                           "Other Endocrine, Nutritional or Metabolic Disease or Disorder with or without Minor Intervention",
                           "General Endocrine - Nutritional Or Metabolic - Age", 
                           "General Endocrine - Nutritional Or Metabolic - Age 0 - 5 Yrs",
                           "General Endocrine - Nutritional Or Metabolic - Age 6 + Yrs",
                           "General Endocrine - Nutritional Or Metabolic - with Minor Investigative Technology - Age 0 - 5 Yrs", 
                           "General Endocrine - Nutritional Or Metabolic - with Minor Investigative Technology - Age 6+ Yrs", 
                           "General Endocrine - Nutritional Or Metabolic with",
                           "General Endocrine - Nutritional Or Metabolic with Minor Investigative Technology - Age 0 - 5 Yrs",
                           "General Endocrine - Nutritional Or Metabolic with Minor Investigative Technology - Age 6+ Yrs",
                           "Management Diabetes - Age 0 - 17 Yrs",
                           "MANAGEMENT GENERAL ENDOCRINE, NUTRITIONAL OR METAB")

ent_dental_ophtho <- c("Dental And Oral Disorders Including Jaw",
                       "Disease or Disorder Ear (excl. inner), Nose or Throat (excl. URI) with Minor Intervention", 
                       "Disease or Disorder Ear, Nose or Throat",
                       "Disease or Disorder Eye", 
                       "Disease or Disorder of the Ear (excl. Inner), Nose or Throat",
                       "Disease or Disorder of the Eye with or without Minor Intervention", 
                       "Disease or Disorder of the Inner Ear with or without Minor Intervention", 
                       "Ear Nose Throat Disorders",
                       "EYE - GRADE 1",
                       "Otitis Media",
                       "OTITIS MEDIA",
                       "Percutaneous Needle Lymph Intervention",
                       "Ophthalmology", 
                       "Ophthalmology with Minor Investigation",
                       "Ophthalmology with Minor Investigative Technology",
                       "OTHER INTERNAL EAR PROCEDURES",
                       "Foreign Body Eye, Ear, Nose or Throat with or without Minor Intervention",
                       "Foreign Body Eye, Ear, Nose/Throat",
                       "Foreign Body Eyes/Ears/Nose",
                       "General Ent", 
                       "General ENT", 
                       "General Ent with Minor Investigation",
                       "General ENT with Minor Investigative Technology",
                       "Intervention on Eyelid  - Grade 1",
                       "MANAGEMENT GENERAL ENT",
                       "MANAGEMENT OPHTHALMOLOGY, AGE 0 - 44 YRS",
                       "Minor Ear Intervention", 
                       "Minor Intervention on Oral Cavity/Pharynx/Glottis", 
                       "MINOR INVESTIGATIVE GENERAL ENT",
                       "Open Wound Eye")

gi_liver <- c("Digestive System Condition with Acute Admission/Tr", 
              "Digestive System Condition with Acute Admission/Transfer", 
              "Disease or Disorder Digestive System",
              "Disease or Disorder of the Digestive System with or without Minor Intervention",
              "Disease or Disorder of the Digestive/Hepatobiliary System with Moderate Intervention",
              "Disease or Disorder of the Hepatobiliary System with or without Minor Intervention",
              "Disease/Disorder Digestive/Hepato System with Acute Admission/Transfer without High Resource Int",
              "General Gastrointestinal - Age 0 - 17 Yrs", 
              "General Gastrointestinal - Age 18 - 44 Yrs",
              "General Gastrointestinal - with Minor Investigatio", 
              "General Gastrointestinal - with Minor Investigation Age 0 - 17 Y",
              "General Gastrointestinal with Minor Investigative",
              "General Gastrointestinal with Minor Investigative Technology Age 0 - 17 Y",
              "General Gastrointestinal with Minor Investigative Technology Age 18 + Yr",
              "Gi Bleed - Perforation Or Obstruction",
              "GI Bleed - Perforation Or Obstruction",
              "Hepatobiliary And Pancreas", 
              "Hepatobiliary And Pancreas with Minor Investigation",
              "Hepatobiliary And Pancreas with Minor Investigative Technology",
              "Interventions Generally Performed by non Emergency Department Service: GI",
              "Major Digestive Intervention on Other Site",
              "MANAGEMENT GENERAL GASTROINTESTINAL, AGE 0 - 17 YR", 
              "MINOR INVESTIGATIVE GENERAL GASTROINTESTINAL, AGE", 
              "Minor Digestive Intervention",
              "Minor Digestive Intervention - Local/No Anaesthesia/Other Unmonitored")

gyne_uro <- c("Disease or Disorder Female Anatomy",
              "Disease or Disorder Male Anatomy", 
              "Disease or Disorder of the Female Anatomy with or without Minor Intervention",
              "Disease or Disorder of the Male Anatomy with or without Minor Intervention", 
              "Disease/Disorder Genitourinary System with Acute Admission/Transfer without High Resource Interv",
              "Pregnancy and Conditions of the Puerperium with or without Minor Intervention",
              "Pregnancy with Uncomplicated Abortive Outcome",
              "Other General Genitourinary Disorders", 
              "Other Genitourological Disorders - Age 0 - 17 Yrs",
              "Other Genitourological Disorders - Age 18 + Yrs", 
              "Other Genitourological Disorders with Minor Investigative Technology - Age 0 - 17 Yrs", 
              "Other Gynecological Intervention - Grade 1",
              "Other Disease or Disorder of the Urinary System with or without Minor Intervention", 
              "Other Disease or Disorder Urinary System", 
              "General Female Genital Disorders - Age 0 - 17 Yrs",
              "General Female Genital Disorders with Minor Invest", 
              "General Female Genital Disorders with Minor Investigative Technology", 
              "General Male Genital Disorders - Age 0 - 17 Yrs", 
              "General Male Genital Disorders - Age 18 + Yrs",
              "General Male Genital Disorders with Minor Investig", 
              "General Male Genital Disorders with Minor Investigative Technology",
              "Lower Urinary Intervention - Grade 2",
              "MANAGEMENT GENERAL FEMALE GENITAL DISORDERS, AGE 0", 
              "Management General Male Genital Disorders - Age 0",
              "Management General Male Genital Disorders - Age 0 - 17 Yrs",
              "Management General Male Genital Disorders - Age 18", 
              "MANAGEMENT GENERAL MALE GENITAL DISORDERS, AGE 0 -", 
              "Management Other Genitourological Disorders - Age", 
              "Management Other Genitourological Disorders - Age 0 - 17 Yrs",
              "MANAGEMENT OTHER GENITOUROLOGICAL DISORDERS, AGE 0",
              "Minor Investigative General Male Genital Disorders",
              "Minor Investigative Other Genitourological Disorde",
              "MINOR INVESTIGATIVE OTHER GENITOUROLOGICAL DISORDE",
              "Minor Investigative Other Genitourological Disorders - Age 0 - 17 Yrs", 
              "Abuse Or Sexual Assault",
              "Contraception")

heme_onc <- c("Chemotherapy",
              "Disease or Disorder Blood or Blood Forming Organ",
              "Disease or Disorder Blood or Blood Forming Organ with or without Minor Intervention", 
              "Epistaxis",
              "Transfusion", 
              "TRANSFUSIONS",
              "Haematology", 
              "Haematology with Minor Investigative Technology", 
              "Management Haematology", 
              "MANAGEMENT HAEMATOLOGY, AGE 0 - 17 YRS",
              "Oncology with Minor Investigative Technology",
              "Minor Investigative Haematology",
              "Follow-Up Examination After Treatment for Malignant Neoplasm")

infectious <- c("Acute Upper Respiratory Infection, Influenza with or without Minor Intervention",
                "Contact With Or Carrier Of Communicable Disease",
                "Systemic Infection", 
                "Systemic Infection - Age 0 - 17 Yrs",
                "Systemic Infection - Age 18 + Yrs",
                "Systemic Infection with Minor Investigative Techno", 
                "Systemic Infection with Minor Investigative Technology",
                "Systemic Infection with or without Minor Intervention",
                "Management Systemic Infection - Age 0 - 17 Yrs", 
                "Management Systemic Infection - Age 18 + Yrs",
                "MANAGEMENT SYSTEMIC INFECTION, AGE 0 - 17 YRS", 
                "Minor Investigative Systemic Infection",
                "Infectious Musculoskeletal Disorders")

mental_health <- c("Addiction - No Mental Health Intervention Reported",
                   "Therapeutic Counselling",
                   "THERAPEUTIC COUNSELLING",
                   "Schizophrenia Or Other Psychotic Disorder No Menta", 
                   "Schizophrenia Or Other Psychotic Disorder No Mental Health Intervention",
                   "Re-Assessment - Personality Affective Or Other Men", 
                   "Re-Assessment - Personality Affective Or Other Mental Health Disorder", 
                   "Re-Assessment - Schizophrenia Or Other Psychotic Disorder",
                   "Personality Affective Or Other Mental Health Disor", 
                   "Personality Affective Or Other Mental Health Disorder No Mental Health Intervention",
                   "PERSONALITY, AFFECTIVE AND OTHER MENTAL HEALTH DIS", 
                   "Other Mental Health Intervention - Non Mental Heal", 
                   "Other Mental Health Intervention - Personality Aff", 
                   "Other Mental Health Intervention - Personality Affective Or Other Mental Health Disorder",
                   "Other Mental Health Intervention - Schizophrenia",
                   "Other Mental Health Intervention - Schizophrenia or Other Psychotic Disorder", 
                   "Initial Assessment - Personality Affective Or Other Mental Health Disorder", 
                   "Initial Assessment - Schizophrenia Or Other Psychotic Disorder", 
                   "Mental Health & Psychosocial Condition",
                   "Mental Health Intervention and Other Counselling",
                   "Mental Health or Psychosocial Condition with Acute Admission/Transfer without High Resource Interv", 
                   "Mental Health or Psychosocial Condition with or without Moderate or Minor Intervention")

msk <- c("Closed Fracture And Other Dislocations", 
         "CLOSED FRACTURE AND OTHER DISLOCATIONS", 
         "Closed Fracture Fingers & Toes",
         "Closed Fracture Fingers Or Toes",
         "CLOSED FRACTURE FINGERS OR TOES",
         "Closed Fracture Fingers or Toes with or without Minor Intervention",
         "Closed Fracture Other Site", 
         "Closed Fracture Other Site with or without Minor Intervention", 
         "Closed Reduction - Local/No Anaesthesia/Other Unmo",
         "Closed Reduction - Local/No Anaesthesia/Other Unmonitored",
         "Closed Reduction - Other Nerve Block/Monitored Anaesthesia",
         "CLOSED REDUCTION NO FIXATION",
         "Congenital Musculoskeletal Deformities", 
         "Congenital Musculoskeletal Deformities with Minor",
         "Congenital Musculoskeletal Deformities with Minor Investigative Technology", 
         "Contusion Except Fingers And Toes",
         "CONTUSION EXCEPT FINGERS AND TOES",
         "Contusion Fingers Or Toes",
         "Contusion, Dislocation, Nerve & Other Soft Tissue Injury", 
         "Contusion, Dislocation, Nerve & Other Soft Tissue Injury with or without Minor Intervention",
         "Disease or Disorder Musculoskeletal and Connective", 
         "Disease or Disorder Musculoskeletal and Connective Tissue",
         "Disease or Disorder Musculoskeletal System or Connective Tissue with or without Minor Intervention", 
         "Trauma with Acute Admission/Transfer",
         "Trauma with Acute Admission/Transfer without High Resource Interv",
         "Trauma with Moderate Intervention",
         "Sprains",
         "SPRAINS",
         "Upper Limb Intervention",
         "Rehabilitation - Other Injury And Trauma - Physical Rehab",
         "Removal Internal Fixation Device - Other Bone",
         "OTHER MINOR INJURIES",
         "OTHER MODERATE INJURIES",
         "Other Musculoskeletal And Connective Tissue - Age",
         "Other Musculoskeletal And Connective Tissue - Age 0 - 17 Yrs", 
         "Other Musculoskeletal And Connective Tissue - Age 18 + Yrs",
         "Other Musculoskeletal And Connective Tissue - with", 
         "Other Musculoskeletal And Connective Tissue - with Minor Investigative Technology - Age 0 - 17 Yrs", 
         "Other Inflammation Musculoskeletal And Connective",
         "Other Inflammation Musculoskeletal And Connective Tissue", 
         "Other Inflammation Musculoskeletal And Connective Tissue with Minor Investigative Technology", 
         "Other Injuries", 
         "Other Knee Intervention",
         "OTHER MAJOR INJURIES",
         "Inflammation Musculoskeletal And Connective Tissue", 
         "Inflammation Musculoskeletal And Connective Tissue with Minor Investigative Technology", 
         "MANAGEMENT CONGENITAL MUSCULOSKELETAL DEFORMITIES",
         "MANAGEMENT OTHER INFLAMMATION MUSCULOSKELETAL AND", 
         "MANAGEMENT OTHER MUSCULOSKELETAL AND CONNECTIVE TI",
         "MINOR INVESTIGATIVE INFLAMMATION MUSCULOSKELETAL A",
         "MINOR INVESTIGATIVE OTHER MUSCULOSKELETAL AND CONN",
         "Nasal Intervention without Flap Graft or other Tis",
         "Nasal Intervention without Flap Graft or other Tissue - Local/No Anaesthesia/Other Unmonitored",
         "Open And Closed Fracture Nose", 
         "Open Fracture And Other Dislocations", 
         "OPEN FRACTURE AND OTHER DISLOCATIONS", 
         "Open Fracture Fingers Or Toes", 
         "Open Reduction")

neuro <- c("Cerebrovascular Disorders",
           "Coma",
           "Convulsions", 
           "Convulsions with Minor Investigation",
           "Convulsions with Minor Investigative Technology", 
           "Disease or Disorder Nervous System with Acute Admission/Transfer without High Resource Interv",
           "Vertigo",
           "Vertigo with Minor Investigation",
           "Vertigo with Minor Investigative Technology",
           "Seizure Disorder",
           "Seizure Disorder with or without Minor Intervention",
           "Spinal Tap",
           "Other Nervous System Disorders",
           "Migraine & Headache", 
           "Migraine Headache",
           "Migraine or Headache with or without Minor Intervention", 
           "Other Disease or Disorder of the Nervous System with or without Minor Intervention",
           "Other Disease or Disorder Nervous System",
           "General Nervous System - Age 0 - 64 Yrs",
           "General Nervous System with Minor Investigation", 
           "General Nervous System with Minor Investigative Technology",
           "Head Injury", 
           "HEAD INJURY", 
           "Head Injury with or without Minor Intervention",
           "Headache", 
           "MANAGEMENT GENERAL NERVOUS SYSTEM, AGE 0 - 64 YRS",
           "MANAGEMENT VERTIGO",
           "Meningitis And Encephalitis",
           "Disease/Disorder Endocrine/Metabolism/Nutrition with Acute Adm/Transfer without High Resource Int",
           "Endocrine, Nutritional and Metabolic Disease or Disorder excluding Diabetes")

resp <- c("Severe Respiratory Distress", 
          "Respiratory Condition with Acute Admission/Transfe", 
          "Respiratory Condition with Acute Admission/Transfer",
          "Disease or Disorder of the Respiratory System with or without Minor Intervention", 
          "Disease or Disorder Respiratory System", 
          "Disease or Disorder Respiratory System with Acute Admission/Transfer without High Resource Interv",
          "General Respiratory System - Age 0 - 64 Yrs",
          "General Respiratory System - with Minor Investigat", 
          "General Respiratory System - with Minor Investigation Age 0 - 17",
          "General Respiratory System - with Minor Investigative Technology Age 0 - 17",
          "General Respiratory System - with Minor Investigative Technology Age 18 +",
          "MANAGEMENT GENERAL RESPIRATORY SYSTEM, AGE 0 - 64", 
          "MINOR INVESTIGATIVE GENERAL RESPIRATORY SYSTEM, AG")

lwobs <- c("Left without being seen or Triage and not seen")

other_cacs_dx <- c("Abnormal Lab Or Diagnostic Test",
                   "Complication Of Treatment",
                   "COMPLICATION OF TREATMENT",
                   "Disease or Disorder Neonatal and Congenital",
                   "Disease or Disorder Not Classified Elsewhere with Moderate Intervention", 
                   "Emergency Visit Interventions", 
                   "Examinations/Other Health Factors with Minor Inves", 
                   "Examinations/Other Health Factors with Minor Investigative Technology",
                   "Follow-Up  Or Convalescence with Minor Investigative Technology",
                   "Follow-up Examination and Other Non Emergent Condi", 
                   "Follow-up Examination and Other Non Emergent Condition",
                   "Follow-up Examination and Other Non Emergent Conditions with Minor Intervention",
                   "Follow-up Examination and Other Non Emergent Conditions without Intervention",
                   "Follow-up Examination following Treatment", 
                   "Follow-Up Or Convalescence", 
                   "FOLLOW-UP OR CONVALESCENCE", 
                   "Follow-Up Or Convalescence with Minor Investigative Technology", 
                   "FOREIGN BODY EXCEPT EYES, EARS AND NOSE",
                   "Foreign Body Except Eyes/Ears/Nose",
                   "Foreign Body Excluding Eye/Ear/Nose", 
                   "Foreign Body Other Site (excl. Eye, ENT) with or without Minor Intervention",
                   "General Symptoms Or Examination",
                   "General Symptoms Or Examination with Minor Investigative Technology",
                   "Health Hazard Related To Personal Or Family Histor", 
                   "Interventions Generally Performed by non Emergency Department Service: Other",
                   "Interventions Not Generally Performed in the Emergency Department", 
                   "Major Emergency Visit Intervention",
                   "Management General Symptoms Or Examination", 
                   "MANAGEMENT GENERAL SYMPTOMS OR EXAMINATION", 
                   "Management Neonatal And Congenital",
                   "MANAGEMENT NEONATAL AND CONGENITAL",
                   "Minor Emergency Visit Intervention",
                   "Minor Investigative Examinations And Or Follow-Up", 
                   "Minor Investigative Examinations And Or Follow-Up  Convalescence",
                   "Minor Investigative Examinations And Other Health", 
                   "MINOR INVESTIGATIVE EXAMINATIONS AND OTHER HEALTH", 
                   "Minor Investigative Examinations And Other Health Factors",
                   "Minor Investigative Neonatal And Congenital",
                   "Neonatal And Congenital",
                   "Neonatal and Congenital with Minor Investigative T",
                   "Neonatal and Congenital with Minor Investigative Technology", 
                   "NULL",
                   "Other Condition with Acute Admission/Transfer",
                   "Other Condition with Acute Admission/Transfer without High Resource Interv",
                   "Poisoning",
                   "Poisoning without Intervention", 
                   "Postsurgical Status",
                   "Prophylactic Vaccination", 
                   "PROPHYLACTIC VACCINATION", 
                   "Re-Assessment - Non Mental Health Problem",
                   "Neonatal Condition or Congenital Anomaly Not Classified Elsewhere with or without Minor Intervention",
                   "Routine Antepartum", 
                   "Routine Health Supervision",
                   "ROUTINE HEALTH SUPERVISION",
                   "Screening Examination", 
                   "SCREENING EXAMINATION", 
                   "Screening Examination with Minor Investigative Technology",
                   "Special Screening Examination",
                   "Telephone Visit",
                   "Visit for Explanation of Investigation or Prescription without Intervention")


# chief_complaint
chief_complaints <- c("Abdominal mass/distention",
                      "Abdominal pain",
                      "Abnormal lab/imaging results Bloodwork, Lab Tests",
                      "Abrasion",
                      "Allergic reaction",
                      "Altered level of consciousness",
                      "Anal/Rectal trauma",
                      "Anorexia",
                      "Anxiety/situational crisis",
                      "Apneic spells in infants",
                      "Back pain",
                      "Bite",
                      "Bizarre behaviour",
                      "Blood and body fluid exposure",
                      "Blood in stool/melena rectal / Anal Bleeding",
                      "Burn",
                      "Cardiac arrest (non-traumatic)",
                      "Cast check",
                      "Chemical exposure",
                      "Chemical exposure, eye",
                      "Chest pain - cardiac features",
                      "Chest pain - non-cardiac features NOS, Ribs",
                      "Concern for patient's welfare",
                      "Confusion",
                      "Congenital problem in children",
                      "Constipation",
                      "Cough/congestion",
                      "Cyanosis",
                      "Dental/gum problem pain, Infection",
                      "Depression/suicidal/deliberate self-harm",
                      "Diarrhea",
                      "Difficulty swallowing/dysphagia",
                      "Diplopia",
                      "Direct referral for consultation",
                      "Discharge, ear",
                      "Dressing change",
                      "Ear injury",
                      "Earache",
                      "Edema, generalized",
                      "Electrical injury",
                      "Epistaxis",
                      "Exposure to communicable disease",
                      "Extremity weakness/symptoms of CVA stroke, TIA",
                      "Eye pain",
                      "Eye trauma",
                      "Facial pain (non-traumatic/non-dental) sinus",
                      "Facial trauma",
                      "Feeding difficulties in newborn",
                      "Fever",
                      "Flank pain",
                      "Floppy Child",
                      "Flu-like illness",
                      "Foreign body in rectum",
                      "Foreign body, ear",
                      "Foreign body, eye",
                      "Foreign body, nose",  
                      "Foreign body, skin",
                      "Foreign body, vagina",
                      "Frostbite/cold injury",
                      "Gait disturbance/ataxia",
                      "General weakness [Malaise, Unwell, Lethargy]",
                      "Genital discharge/lesion male / Female",
                      "Genital trauma",
                      "Groin pain/mass",
                      "Hallucinations/delusions",
                      "Head injury",
                      "Headache pain, Migraine",
                      "Heat-related issue",
                      "Hematuria",
                      "Hemoptysis",
                      "Hiccoughs",
                      "Hyperglycemia",
                      "Hypertension",
                      "Hyperventilation",
                      "Hypoglycemia",
                      "Hypothermia",
                      "Imaging test/blood test Results, Findings",
                      "Inconsolable crying",
                      "Insomnia",
                      "Isolated abdominal trauma - blunt",
                      "Isolated chest trauma - blunt",
                      "IV therapy",
                      "Jaundice",
                      "Joint(s) swelling",
                      "Labial swelling female",
                      "Laceration/puncture",
                      "Leg swelling/edema",
                      "Localized swelling/redness",
                      "Loss of hearing",
                      "Lower extremity injury",
                      "Lower extremity pain",
                      "Lumps, bumps, calluses",
                      "Medical device problem",
                      "Menstrual problems",
                      "Minor complaints NOS Observation, No Diagnosis / Symptoms Noted",
                      "Multisystem trauma - blunt",
                      "Nail problem",
                      "Nasal congestion/hay fever",
                      "Nasal trauma",
                      "Nausea and/or vomiting",
                      "Neck swelling/pain",
                      "Neck trauma",
                      "Neonatal jaundice",
                      "Newly Born",
                      "Noxious inhalation",
                      "NULL",
                      "Oliguria",
                      "Oral/esophageal foreign body",
                      "Other skin conditions",
                      "Overdose ingestion",
                      "Pallor/anemia",
                      "Palpitations/irregular heartbeat tachycardia / Bradycardia",
                      "Pediatric disruptive behaviour",
                      "Pediatric gait disorder/painful walk",
                      "Penile swelling male",
                      "Periorbital swelling",
                      "Photophobia",
                      "Polyuria",
                      "Post-operative complications",
                      "Pregnancy issues, <20 wks",
                      "Prescription/medication request IV Therapy, Blood Transfusion",
                      "Pruritus",
                      "Rash",
                      "Recheck eye",
                      "Rectal/perineal anal pain",
                      "Red eye, discharge",
                      "Redness/tenderness, breast",
                      "Removal staples/sutures",
                      "Respiratory arrest",
                      "Respiratory foreign body",
                      "Return visit for therapy",
                      "Ring removal",
                      "Rule out infestation",
                      "Scrotal pain and/or swelling male",
                      "Seizure",
                      "Sensory loss/paresthesia paraesthesia",
                      "Sexual assault SADV",
                      "Shortness of breath sob",
                      "Social problem",
                      "Sore throat",
                      "Spontaneous Bruising",
                      "Sting",
                      "Stridor",
                      "Substance misuse/intoxication",
                      "Substance withdrawal",
                      "Syncope/pre-syncope",
                      "Tinnitus",
                      "Traumatic back/spine injury",
                      "Tremor",
                      "Unilateral reddened hot limb",
                      "Unknown* not On The List",
                      "Upper extremity injury",
                      "Upper extremity pain",
                      "Urinary retention",
                      "URTI complaints",
                      "UTI complaints",
                      "Vaginal bleed [female]",
                      "Vaginal discharge female",
                      "Vaginal pain/dyspareunia female",
                      "Vertigo dizziness / Dizzy",
                      "Violent/homicidal behaviour",
                      "Visual disturbance blurred",
                      "Vomiting blood",
                      "Wheezing - no other complaints",
                      "Wound check")

cc_cardiac <- c("Cardiac arrest (non-traumatic)",
                "Chest pain - cardiac features",
                "Chest pain - non-cardiac features [NOS, Ribs]",
                "Edema, generalized",
                "General weakness [Malaise, Unwell, Lethargy]",
                "Syncope/pre-syncope",
                "Unilateral reddened hot limb",
                "Leg swelling/edema",
                "Palpitations/irregular heartbeat [tachycardia / Bradycardia]",
                "Hypertension")

cc_ent <- c("Earache",
            "Foreign body, ear",
            "Loss of hearing",
            "Tinnitus",
            "Discharge, ear",
            "Ear injury",
            "Dental/gum problem [pain, Infection]",
            "Facial trauma",
            "Sore throat",
            "Neck swelling/pain",
            "Neck trauma",
            "Difficulty swallowing/dysphagia",
            "Facial pain (non-traumatic/non-dental) [sinus]",
            "Epistaxis",
            "Nasal congestion/hay fever",
            "Nasal trauma",
            "Foreign body, nose", 
            "URTI complaints")

cc_environmental <- c("Frostbite/cold injury",
                      "Noxious inhalation",
                      "Electrical injury",
                      "Chemical exposure",
                      "Hypothermia")

cc_gi <- c("Abdominal mass/distention",
           "Abdominal pain",
           "Constipation",
           "Diarrhea",
           "Foreign body in rectum",
           "Groin pain/mass",
           "Nausea and/or vomiting",
           "Rectal/perineal [anal] pain",
           "Vomiting blood",
           "Blood in stool/melena [rectal / Anal Bleeding]",
           "Jaundice",
           "Hiccoughs",
           "Anal/Rectal trauma",
           "Oral/esophageal foreign body",
           "Feeding difficulties in newborn",
           "Neonatal jaundice")

cc_gu <- c("Flank pain",
           "Hematuria",
           "Genital discharge/lesion [male / Female]",
           "Penile swelling [male]",
           "Genital trauma",
           "Scrotal pain and/or swelling [male]",
           "Urinary retention",
           "UTI complaints",
           "Oliguria",
           "Polyuria")

cc_mental_health <- c("Anorexia",
                      "Anxiety/situational crisis",
                      "Bizarre behaviour",
                      "Concern for patient's welfare",
                      "Depression/suicidal/deliberate self-harm",
                      "Hallucinations/delusions",
                      "Insomnia",
                      "Overdose ingestion",
                      "Pediatric disruptive behaviour",
                      "Social problem",
                      "Substance misuse/intoxication",
                      "Substance withdrawal",
                      "Violent/homicidal behaviour")

cc_neurologic <- c("Confusion",
                   "Altered level of consciousness",
                   "Vertigo [dizziness / Dizzy]",
                   "Headache [pain, Migraine]",
                   "Seizure",
                   "Gait disturbance/ataxia",
                   "Head injury",
                   "Tremor",
                   "Extremity weakness/symptoms of CVA [stroke, TIA]",
                   "Sensory loss/paresthesia [paraesthesia]",
                   "Floppy Child")

cc_ob_gyn <- c("Labial swelling [female]",
               "Pregnancy issues, <20 wks",
               "Vaginal bleed [female]",
               "Menstrual problems","Foreign body, vagina",
               "Vaginal discharge [female]",
               "Vaginal pain/dyspareunia [female]",
               "Sexual assault [SADV]")

cc_ophtho <- c("Chemical exposure, eye",
               "Foreign body, eye",
               "Visual disturbance [blurred]",
               "Eye pain",
               "Red eye, discharge",
               "Photophobia",
               "Diplopia",
               "Periorbital swelling",
               "Eye trauma",
               "Recheck eye")

cc_ortho <- c("Back pain",
              "Traumatic back/spine injury",
              "Upper extremity injury",
              "Upper extremity pain",
              "Lower extremity injury",
              "Lower extremity pain",
              "Joint(s) swelling",
              "Pediatric gait disorder/painful walk")

cc_resp <- c("Shortness of breath [sob]",
             "Respiratory arrest",
             "Cough/congestion",
             "Hyperventilation",
             "Hemoptysis",
             "Respiratory foreign body",
             "Allergic reaction",
             "Stridor",
             "Wheezing - no other complaints",
             "Apneic spells in infants")

cc_derm <- c("Bite",
             "Cyanosis",
             "Sting",
             "Abrasion",
             "Laceration/puncture",
             "Burn",
             "Blood and body fluid exposure",
             "Pruritus",
             "Rash",
             "Localized swelling/redness",
             "Wound check",
             "Other skin conditions",
             "Lumps, bumps, calluses",
             "Redness/tenderness, breast",
             "Rule out infestation",
             "Spontaneous Bruising",
             "Foreign body, skin",
             "Nail problem")

cc_substance_misuse <- c("Substance misuse/intoxication",
                         "Substance withdrawal",
                         "Overdose ingestion")

cc_trauma <- c("Isolated abdominal trauma - blunt",
               "Isolated chest trauma - blunt",
               "Multisystem trauma - blunt")

cc_general_minor <- c("Exposure to communicable disease",
                      "Fever",
                      "Hyperglycemia",
                      "Hypoglycemia",
                      "Direct referral for consultation",
                      "Dressing change",
                      "Removal staples/sutures",
                      "Cast check",
                      "Imaging test/blood test [Results, Findings]",
                      "Medical device problem",
                      "Prescription/medication request [IV Therapy, Blood Transfusion]",
                      "Ring removal",
                      "Abnormal lab/imaging results [Bloodwork, Lab Tests]",
                      "Pallor/anemia",
                      "Post-operative complications",
                      "Minor complaints NOS [Observation, No Diagnosis / Symptoms Noted]",
                      "Inconsolable crying",
                      "Congenital problem in children",
                      "Newly Born",
                      "Flu-like illness",
                      "Heat-related issue",
                      "IV therapy",
                      "Unknown* [not On The List]",
                      "Return visit for therapy")

# dispositions
dispositions <- c("Admit to reporting facility as inpatient to another unit from amb care",
                  "Admitted as an in-patient (in own facility)",
                  "Discharge Home.  No supports",
                  "Discharged Home (no Support Services)",
                  "Discharged home with support services:  (Nursing / Retirement Home, Chronic Care, Home Care, Jail)",
                  "Home Care / Community Support Services",
                  "Intra facility transfer to Day Surgery",
                  "Intra-facility transfer to clinic",
                  "Intra-facility transfer to Clinic",
                  "Intra-facility transfer to ED",
                  "Intra-facility transfer to Emergency Department",
                  "LAMA:  Client left against medical advice",
                  "LBVC:  Client Left After MD Assessment.  Treatment Did Not Occur.",
                  "Left After Physician Assessment -  [LBVC / LAMA:  No Treatment]",
                  "Left after Treatment started  [LBVC / LAMA:  Treatment Started]",
                  "Left post Triage [LWBS]:  Physician Assessment  did not occur.",
                  "LWBS:  Client triaged and left ER Prior To MD Assessment",
                  "Transfer to another acute care facility directly from amb care",
                  "Transfer to Group/supportive living [Retirement Home; Transitional Housing]",
                  "Transfer to Residential Care / Nursing Home (24 hour care)",
                  "Transfered to another acute care facility")

home <- c("Discharge Home.  No supports",
          "Discharged Home (no Support Services)",
          "Discharged home with support services:  (Nursing / Retirement Home, Chronic Care, Home Care, Jail)",
          "Home Care / Community Support Services")

admit_or_transfer_to_facility <- c("Admit to reporting facility as inpatient to another unit from amb care",
                                   "Admitted as an in-patient (in own facility)",
                                   "Intra facility transfer to Day Surgery",
                                   "Intra-facility transfer to clinic",
                                   "Intra-facility transfer to Clinic",
                                   "Intra-facility transfer to ED",
                                   "Intra-facility transfer to Emergency Department",
                                   "Transfer to another acute care facility directly from amb care",
                                   "Transfer to Group/supportive living [Retirement Home; Transitional Housing]",
                                   "Transfer to Residential Care / Nursing Home (24 hour care)",
                                   "Transfered to another acute care facility")

lwobs_ama <- c("LAMA:  Client left against medical advice",
           "LBVC:  Client Left After MD Assessment.  Treatment Did Not Occur.",
           "Left After Physician Assessment -  [LBVC / LAMA:  No Treatment]",
           "Left after Treatment started  [LBVC / LAMA:  Treatment Started]",
           "Left post Triage [LWBS]:  Physician Assessment  did not occur.",
           "LWBS:  Client triaged and left ER Prior To MD Assessment")
